feature (tei export): add link to obtain a letter as TEI/XML
dasch-swiss/beol pull request #135
Opened 2019-03-21 09:43 UTC by tobiasschweizer

closes #76

2019-03-22 16:39 UTC, subotic approved these changes
LGTM, thanks :-)

2019-04-05 07:07 UTC, tobiasschweizer commented
@SepidehAlassi I am thinking about making the TEI link generation code a directive.

2019-04-05 11:56 UTC, SepidehAlassi commented
@tobiasschweizer that is a good idea!

2019-04-12 10:04 UTC, tobiasschweizer commented
@SepidehAlassi I made it a directive. It only creates a TEI link if there is a proper config element.

2019-04-30 10:40 UTC, tobiasschweizer commented
@SepidehAlassi Could you have a look at this PR?

2019-04-30 12:54 UTC, SepidehAlassi commented
![](https://github.trello.services/images/mini-trello-icon.png) [TEI export](https://trello.com/c/8dR7x3Iu/143-tei-export)

2019-04-30 15:16 UTC, SepidehAlassi commented
@tobiasschweizer now that you have removed the config for the letter, is there anything I else I should change for checking this PR?

2019-04-30 16:26 UTC, tobiasschweizer commented
@SepidehAlassi you just have to provide the settings in the config (https://github.com/dhlab-basel/beol/blob/develop/src/config/config.dev.json) like in the test for the directive:

```
{
	            ...
	            'tei': {
	                'http://0.0.0.0:3333/ontology/0801/beol/v2#letter': {
	                    'textProperty': 'http://0.0.0.0:3333/ontology/0801/beol/v2#hasText',
	                    'mappingIRI': 'http://rdfh.ch/projects/yTerZGyxjZVqFMNNKXCDPF/mappings/BEOLTEIMapping',
	                    'gravsearchTemplateIri': 'http://rdfh.ch/0801/templateIri',
	                    'teiHeaderXSLTIri': 'http://rdfh.ch/0801/headerIri'
	                }
	            }
	        }
```

You get the settings when you run the Python script in Knora (https://github.com/dhlab-basel/Knora/blob/develop/webapi/_test_data/test_route/texts/beol/beolTEI.py).

2019-04-30 16:29 UTC, tobiasschweizer commented
But actually this PR is just about generating the link and display it, so it is actually enough to look at the directive.

2019-05-03 10:01 UTC, SepidehAlassi commented
@tobiasschweizer I see that the link is created for a letter as
`<span _ngcontent-c24="" appteilink="" ng-reflect-resource-type="http://0.0.0.0:3333/ontology/0" ng-reflect-resource-iri="http://rdfh.ch/0801/4uMWaXMsT1"></span>`
if I inspect the html, but nothing is displayed in the GUI.
I can not fully understand how is the user supposed to use this link? In one of the previous PRs, there was a clickable component which would result in the creation of TEIs, but there is nothing of that sort anymore.

2019-05-03 10:15 UTC, SepidehAlassi commented
@tobiasschweizer I see, now all works. I had a problem with configuration, it did not show me the link.

2019-05-03 10:17 UTC, SepidehAlassi requested changes

2019-05-03 10:17 UTC, SepidehAlassi commented on src/app/resource/letter/letter.component.html
> +            </section>
I believe it is better to have this link displayed on the right top corner of the letter template. As it is now, the user has to scroll down to end to see the link. 
Most users like to see the things in a first glance without having to scroll.

2019-05-06 07:53 UTC, tobiasschweizer commented on src/app/resource/letter/letter.component.html
> +            </section>
done in https://github.com/dhlab-basel/beol/pull/135/commits/31a829fe672a482ba69d2ec84a4baad6a2c2510b

the link is now shown above the letter's text

2019-05-06 08:36 UTC, tobiasschweizer commented
top right placement:  https://github.com/dhlab-basel/beol/pull/135/commits/ab96df08da50db9bf8f24c12ae07c2618d7fbc6a

2019-05-06 08:39 UTC, SepidehAlassi approved these changes

2019-05-06 08:48 UTC, merged