feature (ForwardFullTextSearch) start with full text search forwarding
dasch-swiss/beol pull request #147
Opened 2019-06-20 03:33 UTC by SepidehAlassi

2019-06-20 04:01 UTC, SepidehAlassi commented
![](https://github.trello.services/images/mini-trello-icon.png) [integration of Leibniz](https://trello.com/c/MBuLxc7x/139-integration-of-leibniz)

2019-06-20 04:03 UTC, SepidehAlassi commented
![](https://github.trello.services/images/mini-trello-icon.png) [full text search in 3rd part repos](https://trello.com/c/TESgAfpI/148-full-text-search-in-3rd-part-repos)

2019-06-20 04:04 UTC, SepidehAlassi commented
![](https://github.trello.services/images/mini-trello-icon.png) [full text search in the 3rd party repos](https://trello.com/c/TESgAfpI/148-full-text-search-in-the-3rd-party-repos)

2019-06-25 10:26 UTC, flavens approved these changes
@SepidehAlassi everything looks good to me. Just one little detail: the loading of search results takes quite some time.. it may be my current connection

2019-07-01 09:45 UTC, SepidehAlassi commented
@flavens Thank you for reviewing this, I asked @tobiasschweizer to check it also regarding the computation time. If it seems critical, I might need to optimise the code a bit.

2019-07-03 11:07 UTC, tobiasschweizer commented
The ontology cache does not work correctly when doing several async search requests because the result is not written back completely before doing new requests for the same ontology. This results in unnecessary calls to the Knora ontology route.

The easiest way to solve this problem would be the caching of all relevant ontologies at the very beginning. But I would really like to look for a better solution so that the ontology cache handles this by itself.

2019-07-03 11:08 UTC, tobiasschweizer requested changes
I think it would be good to have checkboxes for Leibniz and Newton where the full text search can be activated for this repos, too.

2019-07-23 14:22 UTC, SepidehAlassi commented
@tobiasschweizer can you please review this again?
I believe now that the text search is faster, we can safely ignore adding a checkbox

2019-07-24 12:56 UTC, tobiasschweizer requested changes

2019-07-24 12:56 UTC, tobiasschweizer commented on src/app/search-results/search-results.component.ts
> +    externalResults = [];
I think this never used.

2019-07-24 12:56 UTC, tobiasschweizer commented on src/app/search-results/search-results.component.ts
> +                    this.numberOfAllResults += 1 ;
`numberOfAllResults` is used to calculate the max offset for Knora:

```ts
this.maxOffset = Math.floor((this.numberOfAllResults - 1) / this._appInitService.getSettings().pagingLimit);
```

 It shouldn't be changed by adding external hits. Instead, there could be a variable for the Knora results only and a count that combines Knora results and external hits. The overall count can be shown in the template.

2019-07-24 12:56 UTC, tobiasschweizer commented on src/app/search-results/search-results.component.ts
> +            this._cacheService.getEntityDefinitionsForOntologies([this._appInitService.getSettings().ontologyIRI + '/ontology/0801/beol/v2']).subscribe((info2: OntologyInformation) => {
Could you add comment why this is necessary (cache problem) and fix the indentation?

2019-07-24 12:56 UTC, tobiasschweizer commented on src/index.html
> +                        fonts: "STIXGeneral, 'Arial Unicode MS'"
Why is this necessary? Leibniz?

2019-07-24 16:57 UTC, SepidehAlassi commented on src/index.html
> +                        fonts: "STIXGeneral, 'Arial Unicode MS'"
yes

2019-07-24 16:57 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +            this._cacheService.getEntityDefinitionsForOntologies([this._appInitService.getSettings().ontologyIRI + '/ontology/0801/beol/v2']).subscribe((info2: OntologyInformation) => {
ok

2019-07-25 06:23 UTC, tobiasschweizer commented on src/app/search-results/search-results.component.ts
> +                FILTER(?letterNumber = "${letterIdentifier}"^^<http://www.w3.org/2001/XMLSchema#string>)
An idea to avoid doing one Gravsearch query per Newton letter: Could you try using an OR in the filter to match for several letter ids?

2019-07-25 09:23 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +    externalResults = [];
removed!

2019-07-25 10:11 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +                    this.numberOfAllResults += 1 ;
done!

2019-07-25 14:28 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +                FILTER(?letterNumber = "${letterIdentifier}"^^<http://www.w3.org/2001/XMLSchema#string>)
done!

2019-07-25 14:29 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +            this._cacheService.getEntityDefinitionsForOntologies([this._appInitService.getSettings().ontologyIRI + '/ontology/0801/beol/v2']).subscribe((info2: OntologyInformation) => {
done!

2019-07-25 14:30 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +                FILTER(?letterNumber = "${letterIdentifier}"^^<http://www.w3.org/2001/XMLSchema#string>)
@tobiasschweizer I applied your suggestions, can you please check again?

2019-07-25 14:30 UTC, SepidehAlassi commented
@tobiasschweizer I applied your suggestions, can you please check again?

2019-07-29 07:19 UTC, tobiasschweizer approved these changes
I like it! :-) Thanks!



I will try to come up with a solution for the cache so that there could be several async requests for the same ontology. This will be part of https://github.com/dhlab-basel/knora-api-js-lib

2019-07-29 07:19 UTC, tobiasschweizer commented on src/app/search-results/search-results.component.ts
> +     * make search expersion to be sent to search route of Briefportal Leibniz
detail: expression (instead of "expersion")

2019-07-29 08:27 UTC, SepidehAlassi commented on src/app/search-results/search-results.component.ts
> +     * make search expersion to be sent to search route of Briefportal Leibniz
danke!

2019-07-29 08:57 UTC, merged