route for person with GND or VIAF
dasch-swiss/beol pull request #152
Opened 2019-07-04 10:44 UTC by SepidehAlassi

a route to retrieve a person with its GND or VIAF number

2019-07-23 14:22 UTC, SepidehAlassi commented
@tobiasschweizer can you please review this?

2019-07-24 16:04 UTC, tobiasschweizer requested changes

2019-07-24 16:04 UTC, tobiasschweizer commented on src/app/person-route/person-route.component.ts
> +                const query = this._beolService.searchForPerson(this.gndNumber);
Couldn't you just make one query and require the prefix (`(DE-588)` or `(VIAF)`)?

2019-07-24 16:04 UTC, tobiasschweizer commented on src/app/person-route/person-route.component.ts
> +                const query = this._beolService.searchForPerson(this.gndNumber);
In case the prefix causes a problem in the route because of the parentheses, could the client omit the parentheses? And then you could just add them so you can do the Gravsearch query.

2019-07-24 16:04 UTC, tobiasschweizer commented on src/app/services/beol.service.ts
> +            FILTER(?personGndNumber = "${gndNumber}"^^<http://www.w3.org/2001/XMLSchema#string>)
If you don't want to enforce the prefix, Instead of two queries, you could also do this:

```
FILTER(?personGndNumber = "(DE-588)${gndNumber}" || ?personGndNumber = "(VIAF)${gndNumber}")
```

But here I see the danger of collision between GND and VIAF.

2019-07-25 15:03 UTC, SepidehAlassi commented on src/app/person-route/person-route.component.ts
> +                const query = this._beolService.searchForPerson(this.gndNumber);
yeah, well how can I add the parentheses without knowing if client has entered VIAF or GND with (DE-588)? 
VIAF is four character long but DE-588 is 6 character long.

2019-07-25 15:09 UTC, SepidehAlassi commented on src/app/services/beol.service.ts
> +            FILTER(?personGndNumber = "${gndNumber}"^^<http://www.w3.org/2001/XMLSchema#string>)
well this danger exists anyway for both following cases:
1. I query first for gnd and if not found for viaf
2. or I combine the two in one filter statement in a query

2019-07-29 07:27 UTC, tobiasschweizer requested changes
I think your test breaks because the argument looks different now (prefix not included).

2019-07-29 07:27 UTC, tobiasschweizer commented on src/app/person-route/person-route.component.ts
> +                console.log(query)
please remove this console.log

2019-07-29 07:27 UTC, tobiasschweizer commented on src/app/person-route/person-route.component.ts
> +            this.param = params.get('gnd')
missing semicolon

2019-07-29 07:28 UTC, tobiasschweizer commented on src/app/services/beol.service.ts
> +            FILTER(?personGndNumber = "${gndNumber}"^^<http://www.w3.org/2001/XMLSchema#string>)
If your are worried about collisions, you could expect an argument like `_DE-588_118560565` or `_VIAF_68789661` and just replace the prefix.

2019-07-29 09:56 UTC, SepidehAlassi commented
@tobiasschweizer I have not yet completed your requested changes, I will do so today and notify you to check the changes.

2019-07-29 09:58 UTC, tobiasschweizer commented
>  I have not yet completed the requested changes of your last review, I will do so today and notify you to check the changes.

Sorry, I was too fast then. Thanks for keeping me up to date.

2019-07-29 15:43 UTC, SepidehAlassi commented
@tobiasschweizer 
instead of forcing the user to follow a specific pattern, I believe it is better to supportSPARQL CONTAINS and SPARQL STARTSTR in gravsearch and then use them in the filter as
FILTER ( STRSTARTS(?personGndNumber, "(DE-588)"^^<http://www.w3.org/2001/XMLSchema#string>) && ?personGndNumber = "(DE-588)${param}"^^<http://www.w3.org/2001/XMLSchema#string> || STRSTARTS(?personGndNumber, "(VIAF)"^^<http://www.w3.org/2001/XMLSchema#string>) && ?personGndNumber = "(VIAF)${param}"^^<http://www.w3.org/2001/XMLSchema#string>) 
then there won't be any collision at all.

This can be done later, I don't think anybody till then might run into collisions.

2019-07-29 16:13 UTC, tobiasschweizer commented
@SepidehAlassi Sorry, I don't understand.

Isn't the problem we have that we simply cannot pass the parentheses contained in the prefix to the component using the route? But the user actually knows the prefix. So we just need to find a way to instruct the component whether it is a GND or VIAF before doing the query. Then no logical OR would be needed in the filter.

So the logic would work as follows:
1. decide what the prefix is 
2. get the number without prefix from the route
3. do a Gravsearch query with the complete identifier 

Maybe 1. could be done by adding an additional parameter.

The config could look like this: 
```ts
{
        path: 'personsearch/:prefix/:gnd',
        component: PersonRouteComponent
    },
``` 

and the in the component you would get: 

> ParamsAsMap {params: {…}}
> keys: (...)
> params: {prefix: "gnd", gnd: "118560565"}

Then the full identifier is simply a combination of the params `prefix` and `gnd`.

2019-07-29 16:41 UTC, SepidehAlassi commented
> * decide what the prefix is
> * get the id without prefix from the route
> * do a Gravsearch query with the complete identifier

We have discussed this suggestions of yours before. It requires the user to provide a prefix without parentheses. However, my suggestion with a check of the start of the string for every gnd number eliminates the need for a prefix. 

- get param which is a number store as (param) 
- for every person check if its gnd number starts with VIAF or DE-588 
- if the value of personGnDNumber property starts with VIAF compare its value with (VIAF)+param
else if the value of the property personGnDNumber starts with (DE-588) compare it with (DE-588)+param

the above if-else is the expression inside the filter command of gravsearch which I have given in the previous comment

As you see in this way, there will not be any need for a prefix given by the user, and no collision might occur.

2020-08-04 08:00 UTC, closed without merging